"""ProductProfile — structured extraction from user text.

No numerical simulation parameters. Only what the user stated + gaps.
"""

from typing import Literal

from pydantic import BaseModel, Field


# v2-middle Wave 2: the four feature categories.
# `polarity` is a free field per feature so an LLM can plausibly mark a
# `core_value` score as negative for a genuinely weak core-value dimension
# (cf. "competitor is better on X"). Category determines which agent
# weight applies; polarity routes the feature to gain or loss side.
FeatureCategory = Literal[
    "core_value",
    "social_signal",
    "ongoing_cost",
    "switching_friction_reducer",
]


class Feature(BaseModel):
    """A single product feature in the feature matrix.

    Populated by A4. Semantics:
      - score          : 0-1, how strong the product is on this dimension
      - polarity       : positive → adds to gain; negative → adds to loss
      - category       : which archetype weight applies
      - certainty      : subjective P(feature delivers its stated score);
                         passed through T&K probability weighting w(p)
      - visibility     : 0-1, can others see the agent using this feature
      - time_to_value_months : continuous; drives hyperbolic discounting
      - evidence_refs  : list of quote_ids (populated by A2/A3 in Wave 4)
    """

    name: str
    score: float
    polarity: Literal["positive", "negative"]
    category: FeatureCategory
    certainty: float = 0.5
    visibility: float = 0.3
    time_to_value_months: float = 0.0
    basis: str = ""
    evidence_refs: list[str] = Field(default_factory=list)


class CompetitorInfo(BaseModel):
    """A competitor mentioned by the user or discovered via research."""

    name: str
    price: float | None = None
    price_model: str | None = None  # "subscription", "one-time", "freemium", "free"
    has_free_tier: bool = False
    market_position: str | None = None  # "dominant", "challenger", "niche"
    source_url: str | None = None

    # v2-middle Wave 2: per-competitor scores on the same feature names
    # used by this product. Filled as placeholders by A4 in Wave 2;
    # replaced with scraped values by A2 in Wave 4.
    feature_scores: dict[str, float] = Field(default_factory=dict)


class ResearchQuery(BaseModel):
    """A single research query with stopping conditions."""

    query: str
    goal: str
    confidence_threshold: float = 0.7
    fallback_assumption: str | None = None


class OptionalQuery(BaseModel):
    """A conditional research query that fires only if trigger is met."""

    query: str
    goal: str
    trigger_condition: str


class ResearchPlan(BaseModel):
    """The research plan generated by the understand stage."""

    priority_queries: list[ResearchQuery] = Field(default_factory=list)
    optional_queries: list[OptionalQuery] = Field(default_factory=list)


class ProductProfile(BaseModel):
    """Structured extraction from user's product description.

    Contains NO numerical simulation parameters — those come from calibrate.
    Only price is allowed (if the user explicitly stated it).
    """

    name: str
    price: float | None = None
    price_model: str | None = None  # "subscription", "one-time", "freemium", "free"
    billing_period: str | None = None  # "monthly", "annual", "one-time"
    competitors: list[CompetitorInfo] = Field(default_factory=list)
    target_audience: str | None = None
    target_audience_inferred: bool = False  # True if LLM guessed, not user-stated
    value_proposition: str | None = None
    category: str | None = None
    missing_information: list[str] = Field(default_factory=list)
    raw_description: str = ""

    research_plan: ResearchPlan = Field(default_factory=ResearchPlan)
