"""ProductProfile — structured extraction from user text.

No numerical simulation parameters. Only what the user stated + gaps.
"""

from pydantic import BaseModel, Field


class CompetitorInfo(BaseModel):
    """A competitor mentioned by the user or discovered via research."""

    name: str
    price: float | None = None
    price_model: str | None = None  # "subscription", "one-time", "freemium", "free"
    has_free_tier: bool = False
    market_position: str | None = None  # "dominant", "challenger", "niche"
    source_url: str | None = None


class ResearchQuery(BaseModel):
    """A single research query with stopping conditions."""

    query: str
    goal: str
    confidence_threshold: float = 0.7
    fallback_assumption: str | None = None


class OptionalQuery(BaseModel):
    """A conditional research query that fires only if trigger is met."""

    query: str
    goal: str
    trigger_condition: str


class ResearchPlan(BaseModel):
    """The research plan generated by the understand stage."""

    priority_queries: list[ResearchQuery] = Field(default_factory=list)
    optional_queries: list[OptionalQuery] = Field(default_factory=list)


class ProductProfile(BaseModel):
    """Structured extraction from user's product description.

    Contains NO numerical simulation parameters — those come from calibrate.
    Only price is allowed (if the user explicitly stated it).
    """

    name: str
    price: float | None = None
    price_model: str | None = None  # "subscription", "one-time", "freemium", "free"
    billing_period: str | None = None  # "monthly", "annual", "one-time"
    competitors: list[CompetitorInfo] = Field(default_factory=list)
    target_audience: str | None = None
    target_audience_inferred: bool = False  # True if LLM guessed, not user-stated
    value_proposition: str | None = None
    category: str | None = None
    missing_information: list[str] = Field(default_factory=list)
    raw_description: str = ""

    research_plan: ResearchPlan = Field(default_factory=ResearchPlan)
